#!/bin/bash

echo "🔧 Configuração do GitHub OAuth"
echo "================================"
echo ""
echo "1. Acesse: https://github.com/settings/developers"
echo "2. Clique em 'New OAuth App'"
echo "3. Preencha:"
echo "   - Application name: Nerdino"
echo "   - Homepage URL: http://localhost:3000"
echo "   - Authorization callback URL: http://localhost:3000/api/auth/callback/github"
echo "4. Clique em 'Register application'"
echo "5. Copie o Client ID e Client Secret"
echo ""
echo "Depois execute:"
echo "nano .env.local"
echo ""
echo "E substitua as linhas vazias:"
echo "GITHUB_CLIENT_ID=\"\""
echo "GITHUB_CLIENT_SECRET=\"\""
echo ""
echo "Por:"
echo "GITHUB_CLIENT_ID=\"seu_client_id_aqui\""
echo "GITHUB_CLIENT_SECRET=\"seu_client_secret_aqui\""
echo ""
echo "Salve o arquivo e reinicie o servidor:"
echo "npm run dev"
